## Assignment # 1

Hey guys. This is your first assignment for Linear Algebra. Its just to check how much you guys are good with programming to achieve simple matrix operations. Feel free to code in Python. Don't use inbuilt functions. Create your own.



Mail your files to amritansh.48@gmail.com



In [1]:
import numpy as np

**Q1**. Intialize 3 different matrices of following dimensions : (5 x 5 ), (7 x 8 x 9), (10 x 13 x 5 x 7). Use random integers as inputs. Print them out.

In [2]:
a = np.random.randint(1,25,(5,5))
print("a")
print(a)
print()
b= np.random.randint(1,72,(7,8,9))
print("b")
print(b)
print()
c= np.random.randint(1,35,(10,13,5,7))
print("c")
print(c)

a
[[ 1 13  8 15 17]
 [23  5 18 19 13]
 [23  2 10 17  8]
 [16 18  7  8  5]
 [ 2 20 12 17 15]]

b
[[[47 58 16 32 10 33  4 60 59]
  [28 51  1 11 54 41 27 50 50]
  [57 43 70 47 32 17 30 36  9]
  [40 50 54 66 56 48 13 67 34]
  [68 49 37 50 69 71 46 62 18]
  [35 56 35 51 62 13 45 68 48]
  [ 8 41 32 40 22 30 61 19 56]
  [65 23 52 67  3  1 29 44 15]]

 [[44  3 38 28 55  8 67 32 37]
  [39 38 69 53 16 56 65 17  4]
  [32 54 32 32 61 61 54 52 62]
  [34 62 10 14 68 29 21 23 55]
  [19 44 11 46  8 39 34 23 26]
  [67 33 55 25  4 46  5 15 21]
  [21 57  1 56  1 50 31 11 51]
  [12 42 15 65 42 31  7 35  8]]

 [[65 31 42 70 12  6 54 16 58]
  [47 60 11 12 60 60 30 38 38]
  [ 1 71 59 62 60 27 32 31 30]
  [46 52  6 41 24 45 66 68 70]
  [52 21 14  1  2 11  2  1  8]
  [16 46 50 44 26  3 24 41 48]
  [42  5 41 66 40 62 41 26 13]
  [60 64 58 51 58 21 14 51 11]]

 [[18 10 39  1 66 56  5  6  4]
  [71 51 71 62 59 46 59 19 26]
  [10 55 60  6 63 21 40 42 59]
  [26 16 26 67 12 58 68 27 60]
  [24 63 61 50 17  9 24 67 46]

**Q2. **Addition and substraction 

Take 3 Matrices A , B, C. All have same dimensions ( 5 x 3). 
Perform the follwoing operations and print them out.

a. A + B +C

b. B - C

c. C - A

d. A+C-B

e. A-1

f . B + 2

In [3]:
A = np.random.randint(31,45,(5,3))

B= np.random.randint(16,30,(5,3))

C= np.random.randint(1,15,(5,3))
print(" A + B +C:","\n", A + B +C)
print()
print(" B - C:", "\n", B - C)
print()
print(" C - A:", "\n", C - A)
print()
print(" A+C-B:","\n",  A+C-B)
print()
print(" A-1:",  "\n",A-1)
print()
print(" B + 2:", "\n", B + 2)


 A + B +C: 
 [[68 77 67]
 [68 71 74]
 [67 60 72]
 [53 64 75]
 [53 60 57]]

 B - C: 
 [[ 9 17 12]
 [ 5 16  9]
 [15 10 16]
 [18 11 20]
 [15 17  7]]

 C - A: 
 [[-29 -33 -19]
 [-27 -31 -23]
 [-40 -26 -26]
 [-29 -23 -31]
 [-29 -34 -23]]

 A+C-B: 
 [[30 25 19]
 [34 23 28]
 [29 24 20]
 [13 22 19]
 [17 20 25]]

 A-1: 
 [[38 41 30]
 [38 38 36]
 [43 33 35]
 [30 32 38]
 [31 36 31]]

 B + 2: 
 [[21 28 26]
 [19 26 25]
 [21 20 28]
 [22 23 30]
 [20 22 18]]


**Q 3.** Using the matrices A, B and C from above, and the vector
x = [1, 0, 0]

Perform the following and print them out:

a. A^3

b. B^3 * x

c. C * x

In [4]:
x =np.array([1, 0, 0])

In [5]:
A**3

array([[59319, 74088, 29791],
       [59319, 59319, 50653],
       [85184, 39304, 46656],
       [29791, 35937, 59319],
       [32768, 50653, 32768]], dtype=int32)

In [6]:
(B**3) * x

array([[6859,    0,    0],
       [4913,    0,    0],
       [6859,    0,    0],
       [8000,    0,    0],
       [5832,    0,    0]])

In [7]:
C * x

array([[10,  0,  0],
       [12,  0,  0],
       [ 4,  0,  0],
       [ 2,  0,  0],
       [ 3,  0,  0]])

**Q4**. Using the matrices A, B and C from above, perform the follwoing and print them out:

a. A (Transpose) 

b. C (Transpose ) + B (Transpose)




In [8]:
A.T

array([[39, 39, 44, 31, 32],
       [42, 39, 34, 33, 37],
       [31, 37, 36, 39, 32]])

In [9]:
C.T + (B.T)

array([[29, 29, 23, 22, 21],
       [35, 32, 26, 31, 23],
       [36, 37, 36, 36, 25]])

**Q5**. Print out an identity matrix of (5 x 5) using a function

In [10]:
 
  # your code here
  # it should return/print  an identity matrix of n x n dimension
def indetity_matrix(n):
    i =0
    j = 0
    for var in n:
        if i == j:
            n[i,j]=1
            i+=1
            j+=1
    count = 0
    for row in n:
        row[count+1:] = 0
        count += 1

    count = 0
    for row in n:
        row[:-5+count] = 0
        count += 1
    print(n)
indetity_matrix(np.arange(1,26).reshape(5,5))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


**Q6**. Take 3 matrices of dimension (3 x 3 ) each. Name them as Mat_A, Mat_B, Mat_C. Perform the following :

a. 4 * Mat_A^2 + 12 * Mat_A * Mat_B + 9 * Mat_B^2


b. 2 * Mat_A * (2 * Mat_A + 3 * Mat_B) + 3 * (2 * Mat_A + 3 * Mat_B) * Mat_B

In [11]:
Mat_A = np.random.randint(19,27,(3,3))

Mat_B= np.random.randint(10,18,(3,3))

Mat_C= np.random.randint(1,9,(3,3))

print(Mat_A)
print()
print(Mat_B)
print()
print(Mat_C)
print()

[[23 25 25]
 [26 24 24]
 [23 25 20]]

[[17 14 11]
 [16 17 17]
 [14 10 17]]

[[7 4 7]
 [4 3 3]
 [5 4 5]]



In [12]:
#a.
4 * Mat_A**2 + 12 * Mat_A * Mat_B + 9 * Mat_B**2

array([[ 9409,  8464,  6889],
       [10000,  9801,  9801],
       [ 7744,  6400,  8281]])

In [13]:
#b.
2 * Mat_A * (2 * Mat_A + 3 * Mat_B) + 3 * (2 * Mat_A + 3 * Mat_B) * Mat_B

array([[ 9409,  8464,  6889],
       [10000,  9801,  9801],
       [ 7744,  6400,  8281]])

**Q7**. For any Matrix A write a function to print out is it singular or not?

In [14]:
def isSingular(A) :
    A_ans= ((A[0,0]* A[1,1])-(A[1,0]*A[0,1]))
    if A_ans == 0:
        print('It is Singular Matrix ')
    else:
         print("It's not a Singular Matrix" )
isSingular(np.random.randint(1,4,(2,2)))            

It's not a Singular Matrix


**Q8.** Print out the deteminants of A, B, C

In [15]:
A = np.random.randint(9,12,(2,2))
print(A)
print()
B= np.random.randint(4,8,(2,2))
print(B)
print()
C= np.random.randint(1,4,(2,2))
print(C)
print()

[[ 9 11]
 [10  9]]

[[5 5]
 [6 4]]

[[2 1]
 [1 2]]



In [16]:
A_ans= ((A[0,0]* A[1,1])-(A[1,0]*A[0,1]))
A_ans

-29

In [17]:
B_ans= ((B[0,0]* B[1,1])-(B[1,0]*B[0,1]))
B_ans

-10

In [18]:
C_ans= ((C[0,0]* C[1,1])-(C[1,0]*C[0,1]))
C_ans

3